title: Huajie (Jay) Cao
email: caohuaji@msu.edu
description: Personal academic website
baseurl: ""
url: "https://www.huajiecao.com"
markdown: kramdown
permalink: pretty
plugins: []
exclude:
  - README-draft.md